version: '3'

services:
# ...   
  box1:     
    image: containous/whoami
    container_name: box1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    command: --port 9077
    restart: on-failure
    networks:
      - proxy_aug07

  box2:     
    image: containous/whoami
    container_name: box2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    command: --port 9088
    restart: on-failure
    networks:
      - proxy_aug07

  web:
    image: httpd:2.4-alpine
    container_name: web
    volumes:
      - ./_build/html:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    restart: on-failure
    networks:
      - proxy_aug07

      
networks:
    proxy_aug07:
      external: true

