version: '3'

services:

  traefik:
    image: traefik:v1.7.30-alpine
    command: --docker
    ports:
      - 80:80
      - 443:443
    environment:
      - DO_AUTH_TOKEN
    networks:
      - proxy_aug07
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik/config:/etc/traefik
    labels:
      - "traefik.frontend.rule=Host:phaustin.org;PathPrefixStrip:/traefik"
      - "traefik.port=8080"
    container_name: traefik
    restart: always


networks:
    proxy_aug07:
      driver: bridge
      name: proxy_aug07

