  [backends]
    [backends.backend1]
      [backends.backend1.servers.server1]
      url = "http://box1:9077"
    [backends.backend2]
      [backends.backend2.servers.server1]
      url = "http://box2:9088"
    [backends.backend3]
      [backends.backend3.servers.server1]
      url = "http://web:80"
    [backends.backend4]
      [backends.backend4.servers.server1]
      url = "http://kazarinoff_web:80"

  [frontends]
    [frontends.frontend1]
      backend = "backend1"
      # [frontends.frontend1.routes.test_1]
      # rule = "Host: houston.phaustin.org"
      [frontends.frontend1.routes.test_1]
      rule = "PathPrefixStrip:/box1"
    [frontends.frontend2]
      backend = "backend2"
      [frontends.frontend2.routes.test_1]
      rule = "PathPrefixStrip:/box2"
    [frontends.frontend3]
      backend = "backend3"
      [frontends.frontend3.routes.test_1]
      rule = "Host: web.phaustin.org"
    [frontends.frontend4]
      backend = "backend4"
      [frontends.frontend4.routes.test_1]
      rule = "Host: e211text.phaustin.org"
  
